services:
  pickups:
    build: .
    container_name: netris
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./apache2/config:/etc/apache2/sites-available
      - ./apache2/log:/var/log/apache2
  
